package com.ttv.at.test;

public enum error_code {
	NO_ERROR, UNKNOWN_ERROR, NOT_SUPPORT, REQUIRED_OBJECT, REQUIRE_INPUT, REQUIRE_RETURN, OBJECT_NOT_FOUND, ACTION_FAILED, TEST_FAILED, EXPECTED_NOT_MATCH
}
